apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  day2.tech/app: pomerium

configurations:
- kustomize-config.yaml
namespace: pomerium

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml

configMapGenerator:
  - name: pomerium-policy
    files:
      - policy.yaml
  - name: pomerium
    envs:
    - config.txt

  - name: pomerium-urls
    literals:
    - POMERIUM_AUTHENTICATE_URL=https://$(POMERIUM_AUTHENTICATE_HOST)
    - POMERIUM_FWDAUTH_URL=https://$(POMERIUM_FWDAUTH_HOST)

secretGenerator:
- name: pomerium
  envs:
  - secret.txt
  type: Opaque

vars:
- name: POMERIUM_AUTHORIZE_HOST
  objref:
    kind: ConfigMap
    name: pomerium
    apiVersion: v1
  fieldref:
    fieldpath: data.POMERIUM_AUTHORIZE_HOST
- name: POMERIUM_AUTHENTICATE_HOST
  objref:
    kind: ConfigMap
    name: pomerium
    apiVersion: v1
  fieldref:
    fieldpath: data.POMERIUM_AUTHENTICATE_HOST
- name: POMERIUM_FWDAUTH_HOST
  objref:
    kind: ConfigMap
    name: pomerium
    apiVersion: v1
  fieldref:
    fieldpath: data.POMERIUM_FWDAUTH_HOST
- name: POMERIUM_IDP_PROVIDER
  objref:
    kind: ConfigMap
    name: pomerium
    apiVersion: v1
  fieldref:
    fieldpath: data.POMERIUM_IDP_PROVIDER
- name: CERT_MANAGER_ISSUER
  objref:
    kind: ConfigMap
    name: pomerium
    apiVersion: v1
  fieldref:
    fieldpath: data.CERT_MANAGER_ISSUER
