apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: loki-stack

resources:
- namespace.yaml
- mandatory.yaml


secretGenerator:
- name: loki-stack-grafana
  envs:
  - secret.env
  type: Opaque
