resources:
- namespace.yaml
- external-dns.yaml
- secret.yaml

namespace: external-dns-operator

commonLabels:
  app: external-dns

secretGenerator:
- name: external-dns
  env: secret.env
  type: Opaque
